prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/actionmenu_empty.sql
@@application/shared_components/navigation/lists/radiation_menu_n.sql
@@application/shared_components/navigation/lists/tree_menu.sql
@@application/shared_components/navigation/lists/radiation_menu.sql
@@application/shared_components/navigation/lists/list_rad_app_queue_machines.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/app_icon_min_css.sql
@@application/shared_components/files/skm_pesh_jpg.sql
@@application/shared_components/files/skm_khi_png.sql
@@application/shared_components/files/skm_jpg.sql
@@application/shared_components/files/skm_lhr_png.sql
@@application/shared_components/files/hidepasswordeye_css.sql
@@application/shared_components/files/hidepasswordeye_min_css.sql
@@application/shared_components/files/radiationlogo_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/is_delete_allowed.sql
@@application/shared_components/security/authorizations/is_insert_allowed.sql
@@application/shared_components/security/authorizations/is_page_authorized.sql
@@application/shared_components/security/authorizations/is_update_allowed.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/contigencycheck.sql
@@application/shared_components/logic/application_processes/get_previous_page_id.sql
@@application/shared_components/logic/application_processes/addtofavorite.sql
@@application/shared_components/logic/application_processes/userguide.sql
@@application/shared_components/logic/application_processes/loadimage.sql
@@application/shared_components/logic/application_processes/skmnavigatebackend.sql
@@application/shared_components/logic/application_processes/load_files.sql
@@application/shared_components/logic/application_processes/get_previous_page_url.sql
@@application/shared_components/logic/application_processes/check_readonly.sql
@@application/shared_components/logic/application_items/app_role.sql
@@application/shared_components/logic/application_items/gv_alert_text.sql
@@application/shared_components/logic/application_items/gv_center_type.sql
@@application/shared_components/logic/application_items/gv_connected_server.sql
@@application/shared_components/logic/application_items/gv_copy_right.sql
@@application/shared_components/logic/application_items/gv_cr_location_id.sql
@@application/shared_components/logic/application_items/gv_cr_zone_id.sql
@@application/shared_components/logic/application_items/gv_db_name.sql
@@application/shared_components/logic/application_items/gv_emp_position_location_id.sql
@@application/shared_components/logic/application_items/gv_engine_kill.sql
@@application/shared_components/logic/application_items/gv_live_db.sql
@@application/shared_components/logic/application_items/gv_location_id.sql
@@application/shared_components/logic/application_items/gv_login_time.sql
@@application/shared_components/logic/application_items/gv_order_location_desc.sql
@@application/shared_components/logic/application_items/gv_order_location_id.sql
@@application/shared_components/logic/application_items/gv_organization_id.sql
@@application/shared_components/logic/application_items/gv_page_history.sql
@@application/shared_components/logic/application_items/gv_pc_location.sql
@@application/shared_components/logic/application_items/gv_pc_order_location_id.sql
@@application/shared_components/logic/application_items/gv_physical_location.sql
@@application/shared_components/logic/application_items/gv_physical_location_id.sql
@@application/shared_components/logic/application_items/gv_radiation_queue_defaults.sql
@@application/shared_components/logic/application_items/gv_rad_app_group_id.sql
@@application/shared_components/logic/application_items/gv_rdt_server.sql
@@application/shared_components/logic/application_items/gv_read_only.sql
@@application/shared_components/logic/application_items/gv_reports_envid.sql
@@application/shared_components/logic/application_items/gv_selected_mrno.sql
@@application/shared_components/logic/application_items/gv_select_patient.sql
@@application/shared_components/logic/application_items/gv_terminal.sql
@@application/shared_components/logic/application_items/gv_user_department.sql
@@application/shared_components/logic/application_items/gv_user_department_id.sql
@@application/shared_components/logic/application_items/gv_user_id.sql
@@application/shared_components/logic/application_items/gv_user_location_id.sql
@@application/shared_components/logic/application_items/gv_user_mrno.sql
@@application/shared_components/logic/application_items/gv_user_name.sql
@@application/shared_components/logic/application_items/gv_zone_id.sql
@@application/shared_components/logic/application_items/is_mobile.sql
@@application/shared_components/logic/application_items/login_message.sql
@@application/shared_components/logic/application_items/lv_patient_mrno.sql
@@application/shared_components/logic/application_items/lv_sr_no.sql
@@application/shared_components/logic/application_items/p_assignment_id.sql
@@application/shared_components/logic/application_items/p_task_mrno.sql
@@application/shared_components/logic/application_items/radiation_queue_defaults.sql
@@application/shared_components/logic/application_items/user_image.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/accessorylov.sql
@@application/shared_components/user_interface/lovs/appointmentlov.sql
@@application/shared_components/user_interface/lovs/contrastgivenby.sql
@@application/shared_components/user_interface/lovs/contrastlov.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/lov_consultant_phym.sql
@@application/shared_components/user_interface/lovs/lov_def_planning_parameters.sql
@@application/shared_components/user_interface/lovs/lov_def_rad_queue_alert.sql
@@application/shared_components/user_interface/lovs/lov_def_rad_queue_evensts.sql
@@application/shared_components/user_interface/lovs/lov_def_rad_queue_performance_type.sql
@@application/shared_components/user_interface/lovs/lov_def_workflow_setup_workflow_id.sql
@@application/shared_components/user_interface/lovs/lov_grade.sql
@@application/shared_components/user_interface/lovs/lov_location.sql
@@application/shared_components/user_interface/lovs/lov_mrno.sql
@@application/shared_components/user_interface/lovs/lov_objects.sql
@@application/shared_components/user_interface/lovs/lov_organization1.sql
@@application/shared_components/user_interface/lovs/lov_performance_type.sql
@@application/shared_components/user_interface/lovs/lov_planning_cpt.sql
@@application/shared_components/user_interface/lovs/lov_radiation_no.sql
@@application/shared_components/user_interface/lovs/lov_rad_app_queue_next_event.sql
@@application/shared_components/user_interface/lovs/lov_rad_checklist_performance_type.sql
@@application/shared_components/user_interface/lovs/lov_rad_consent_site.sql
@@application/shared_components/user_interface/lovs/lov_rad_discharge_discharge_order.sql
@@application/shared_components/user_interface/lovs/lov_rad_hdr_implant_insert_medication.sql
@@application/shared_components/user_interface/lovs/lov_rad_hdr_phy_machine.sql
@@application/shared_components/user_interface/lovs/lov_rad_hdr_phy_special_instr.sql
@@application/shared_components/user_interface/lovs/lov_rad_implant_discharge_order.sql
@@application/shared_components/user_interface/lovs/lov_rad_machine_schedule_slot_name.sql
@@application/shared_components/user_interface/lovs/lov_rad_performance_type_event.sql
@@application/shared_components/user_interface/lovs/lov_rad_performance_type_objects.sql
@@application/shared_components/user_interface/lovs/lov_rad_request_trt_intent.sql
@@application/shared_components/user_interface/lovs/lov_rad_schedule_detail_site.sql
@@application/shared_components/user_interface/lovs/lov_toxicity.sql
@@application/shared_components/user_interface/lovs/lv_planning_parameters.sql
@@application/shared_components/user_interface/lovs/lv_rad_physics_fraction.sql
@@application/shared_components/user_interface/lovs/lv_rad_physics_machine.sql
@@application/shared_components/user_interface/lovs/lv_rad_request_doctor.sql
@@application/shared_components/user_interface/lovs/parent_site_lov.sql
@@application/shared_components/user_interface/lovs/radiation_events_employee_lov.sql
@@application/shared_components/user_interface/lovs/rad_orderentry_setup_loc.sql
@@application/shared_components/user_interface/lovs/rad_orderentry_setup_package.sql
@@application/shared_components/user_interface/lovs/rad_orderentry_setup_package_cpt.sql
@@application/shared_components/user_interface/lovs/rad_orderentry_setup_planning.sql
@@application/shared_components/user_interface/lovs/rad_performance_type_location.sql
@@application/shared_components/user_interface/lovs/rad_physicst_short_name.sql
@@application/shared_components/user_interface/lovs/rad_request_neck_position.sql
@@application/shared_components/user_interface/lovs/rad_request_setup_position.sql
@@application/shared_components/user_interface/lovs/rad_request_sim_ct.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/modal_dialog_skmmenu.sql
@@application/shared_components/user_interface/templates/page/modal_dialog_phymenu.sql
@@application/shared_components/user_interface/templates/page/skmtemplate.sql
@@application/shared_components/user_interface/templates/page/frontpage.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/btnadd.sql
@@application/shared_components/user_interface/templates/button/btnapplychanges.sql
@@application/shared_components/user_interface/templates/button/btncancel.sql
@@application/shared_components/user_interface/templates/button/btncreate.sql
@@application/shared_components/user_interface/templates/button/btnprint.sql
@@application/shared_components/user_interface/templates/button/btnreset.sql
@@application/shared_components/user_interface/templates/button/btnsearch.sql
@@application/shared_components/user_interface/templates/button/report.sql
@@application/shared_components/user_interface/templates/button/sign.sql
@@application/shared_components/user_interface/templates/button/exit.sql
@@application/shared_components/user_interface/templates/button/save.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/customstandardregion.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/mobile_menu.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/user_profile.sql
@@application/shared_components/user_interface/templates/report/user_profile_002.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/optional_phymenu.sql
@@application/shared_components/user_interface/templates/label/left_labeled_checkbox.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/ig_tooltip_json.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/plugins/region_type/skm_region_double_sign.sql
@@application/shared_components/plugins/template_component/action_bar.sql
@@application/shared_components/plugins/dynamic_action/skm_call_report6370752912.sql
@@application/shared_components/plugins/dynamic_action/skm_call_report.sql
@@application/shared_components/plugins/process_type/prc_kadeyemiapex_savetodropbox.sql
@@application/shared_components/plugins/process_type/is_mirmas_savefilestodisk.sql
@@application/shared_components/plugins/region_type/de_danielh_dropzone2.sql
@@application/shared_components/plugins/region_type/com_fos_image_slider.sql
@@application/shared_components/plugins/region_type/image_gallery_de_nhasko.sql
@@application/shared_components/plugins/region_type/image_gallery_de_nhasko65451.sql
@@application/shared_components/plugins/region_type/skm_region_sign.sql
@@application/shared_components/plugins/dynamic_action/mho_redirect.sql
@@application/shared_components/plugins/template_component/apex_lufcmattylad_cards_list_ui.sql
@@application/shared_components/plugins/template_component/patientcard_radiation.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00090.sql
@@application/pages/page_00199.sql
@@application/pages/page_01000.sql
@@application/pages/page_09991.sql
@@application/pages/page_09992.sql
@@application/pages/page_09993.sql
@@application/pages/page_09994.sql
@@application/pages/page_09995.sql
@@application/pages/page_09996.sql
@@application/pages/page_09997.sql
@@application/pages/page_09998.sql
@@application/pages/page_09999.sql
@@application/pages/page_99941.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
